name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '1.16.x', '1.15.x', '1.14.x', '1.13.x' ]
    services:
        redis:
          image: redis
          ports:
            - 6379:6379
        postgres:
          image: postgres
          env:
#             POSTGRES_PASSWORD: ''
            POSTGRES_DB: test
            POSTGRES_HOST_AUTH_METHOD: trust
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: |
        go get github.com/stretchr/testify/assert
        go get github.com/vmihailenco/msgpack
        go get github.com/lib/pq
        go get -t -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
