name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
        redis:
          image: redis
        postgres:
          image: postgres
          env:
#             POSTGRES_PASSWORD: ''
            POSTGRES_DB: test
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install dependencies
      run: |
        go get github.com/stretchr/testify/assert
        go get github.com/vmihailenco/msgpack
        go get github.com/lib/pq
        go get -t -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
